name: golangci-lint
run-name: golangci-lint workflow launched by @${{ github.actor }}
on:
  push:
    branches:
      - develop
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Execute golangci-lint
        # https://github.com/golangci/golangci-lint-action
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.2
          install-mode: binary
          only-new-issues: false
          # github-token: xxx # When using only-new-issues option, the GitHub API is used, so a token is required
          # working-directory: somedir
          skip-cache: false
          skip-save-cache: false
          cache-invalidation-interval: 7
          problem-matchers: false
          # args: --config=.golangci.yaml --issues-exit-code=1
